name: Hari-Client PyTest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[tests]

      - name: Get changed files
        id: changes
        run: echo "files=$(git diff --name-only origin/master...${{ github.event.pull_request.head.sha }} | xargs)" >> $GITHUB_OUTPUT

      - name: Run pre-commit on changed files
        run: |
          changed_files="${{ steps.changes.outputs.files }}"
          if [ -n "$changed_files" ]; then
            pre-commit run --files $changed_files || exit 1
          fi

      - name: Run tests with pytest
        run: pytest
